language: node_js
node_js:
  - 10
cache:
  directories:
    node_modules
notifications:
  email: false
script:
  - npm run lint
before_install:
  - openssl aes-256-cbc -K $encrypted_8192a7bdb297_key -iv $encrypted_8192a7bdb297_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
install:
  - npm install
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
  local-dir: dist
